name: 'DotCMS discover stable version'
description: 'From a given DotCMS version discovers the stable Docker tags to '
author: 'Victor Alfaro'
inputs:
  version:
    description: 'DotCMS version usually founf in core/dotCMS/gradle.properties file'
    required: false
    default: 'true'
  hash:
    description: 'Build hash to use to create unique tag'
    required: true
  label:
    description: 'Custom label for tag. Could be anything but values: "SNAPSHOT" and "lts" are special cases'
    required: false
  update_stable:
    description: 'Value that tells to update stable tags as well, possible values: true, false or single'
    required: false
    default: 'true'
  also_latest:
    description: 'Flag that tells to also update "latest" tag (depends on update_stable input to be set to true)'
    required: false
    default: 'false'
  base_tag_size:
    description: 'Number of elements that conform a base stable version (e.g. 2 for "21.05" in 21.05.8)'
    required: false
    default: 2
runs:
  using: node12
  main: dist/index.js
branding:
  icon: 'check'
  color: 'blue'
